
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: customer
      MYSQL_USER: benja
      MYSQL_PASSWORD: 123
    ports:
      - 3307:3306
    networks:
      - microservices
  config-server:
    build: ./services/config-server
    ports:
      - 8888:8888
    networks:
      - microservices
  discovery:
    build: ./service/discovery
    ports:
      - 8761:8761
    depends_on:
      - config-server
    networks:
      - microservices
networks:
  microservices:
