
version: '3.8'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: customer
      MYSQL_USER: benja
      MYSQL_PASSWORD: 123
    ports:
      - 3307:3306
    networks:
      - microservices
  discovery:
    build: discovery
    ports:
      - 8761:8761
    networks:
      - microservices

  customer-service:
    build: customer-service
    ports:
      - 8090:8090
    networks:
      - microservices

  config-server:
    build: config-server
    ports:
      - 8888:8888
    networks:
      - microservices
networks:
  microservices
