services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: customer
      MYSQL_USER: benja
      MYSQL_PASSWORD: 123
    ports:
      - 3307:3306
    networks:
      - microservices

  config-server:
    container_name: config-server
    build: ./services/config-server
    ports:
      - 8888:8888
    networks:
      - microservices

  discovery:
    container_name: discovery
    build: ./services/discovery
    ports:
      - 8761:8761
    networks:
      - microservices

networks:
  microservices:
