
services:
  mysql:
    container_name: mysql
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: customer
      MYSQL_USER: benja
      MYSQL_PASSWORD: 123
    ports:
      - "3307:3306"
    networks:
      - 'microservices'

  config-server:
    container_name: config-server
    build: ./services/config-server
    ports:
      - "8888:8888"
    networks:
      - 'microservices'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  discovery:
    container_name: discovery
    build: ./services/discovery
    ports:
      - "8761:8761"
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - 'microservices'

networks:
  microservices: