server:
  port: 8090
spring:
  jpa:
    hibernate:
      ddlAuto: update
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/customer?serverTimezone=UTC
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka