server:
  port: 8090
spring:
  jpa:
    hibernate:
      ddlAuto: update
  datasource:
    username: benja
    password: 123
    url: jdbc:mysql://db:3307/customer?serverTimezone=UTC
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka