spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/memin09/config-server.git
          searchPaths: configurations
          username: benjamincastaneda783@gmail.com
          password:

